UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img1.jpg', nombre_comercial = 'Impercomex', precio_unitario = 200, unidad_venta = 'cubeta' WHERE "SKU" = 'PPG-0001';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img2.jpg', nombre_comercial = 'PRO 1000 PLUS BLANCO', precio_unitario = 300, unidad_venta = 'cubeta' WHERE "SKU" = 'PPG-0002';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img3.jpg', nombre_comercial = 'RIVER BARNIZ SECADO RAPIDO', precio_unitario = 1500, unidad_venta = 'cubeta' WHERE "SKU" = 'PPG-0003';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img4.jpg', nombre_comercial = 'TOP Autosil', precio_unitario = 567, unidad_venta = 'cubeta' WHERE "SKU" = 'PPG-0004';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img5.jpg', nombre_comercial = 'COLOR CAR PRIMARIO UNIVERSAL', precio_unitario = 1900, unidad_venta = 'cubeta' WHERE "SKU" = 'PPG-0005';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img6.jpg', nombre_comercial = 'POLYFORM BARNIZ BRILLO DIRECTO INDUSTRIAL', precio_unitario = 589, unidad_venta = 'cubeta' WHERE "SKU" = 'PPG-0006';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img7.jpg', nombre_comercial = 'POLYFORM PINTURA 11000', precio_unitario = 478, unidad_venta = 'cubeta' WHERE "SKU" = 'PPG-0007';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img8.jpg', nombre_comercial = 'Effexmetal Mercurio', precio_unitario = 459, unidad_venta = 'cubeta' WHERE "SKU" = 'PPG-0008';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img9.jpg', nombre_comercial = 'Effexmetal Oro', precio_unitario = 1239, unidad_venta = 'cubeta' WHERE "SKU" = 'PPG-0009';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img10.jpg', nombre_comercial = 'POLYFORM FONDO BD F-218', precio_unitario = 400, unidad_venta = 'cubeta' WHERE "SKU" = 'PPG-0010';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img11.png', nombre_comercial = 'Sellador de poliuretano', precio_unitario = 670, unidad_venta = 'tambor' WHERE "SKU" = 'PPG-0011';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img12.jpg', nombre_comercial = 'Sellador silicon blanco', precio_unitario = 899, unidad_venta = 'tambor' WHERE "SKU" = 'PPG-0012';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img13.jpg', nombre_comercial = 'Exito Cepillo picar 210 Cerda Larga', precio_unitario = 430, unidad_venta = 'unidad' WHERE "SKU" = 'PPG-0013';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img14.jpg', nombre_comercial = 'Exito Cepillo de Alambre 64 mango corto', precio_unitario = 1890, unidad_venta = 'unidad' WHERE "SKU" = 'PPG-0014';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img15.jpg', nombre_comercial = 'Rodillo 4 nylon completo Comex', precio_unitario = 2300, unidad_venta = 'unidad' WHERE "SKU" = 'PPG-0015';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img16.jpg', nombre_comercial = 'Exito Charola Premier', precio_unitario = 1345, unidad_venta = 'unidad' WHERE "SKU" = 'PPG-0016';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img17.jpg', nombre_comercial = 'Limpiador aluminio Comex', precio_unitario = 345, unidad_venta = 'unidad' WHERE "SKU" = 'PPG-0017';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img18.jpg', nombre_comercial = 'Limpiador de vidrios Comex', precio_unitario = 579, unidad_venta = 'unidad' WHERE "SKU" = 'PPG-0018';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img19.jpg', nombre_comercial = 'Proteja Comex', precio_unitario = 679, unidad_venta = 'cubeta' WHERE "SKU" = 'PPG-0019';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img20.jpg', nombre_comercial = 'Kit compresor Exito 2.5hp', precio_unitario = 8900, unidad_venta = 'unidad' WHERE "SKU" = 'PPG-0020';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img21.jpg', nombre_comercial = 'Pistola de Succion Reforzada 507 Exito', precio_unitario = 4590, unidad_venta = 'unidad' WHERE "SKU" = 'PPG-0021';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img22.jpg', nombre_comercial = 'Espatula exito Rigida Mango de mad 3', precio_unitario = 299, unidad_venta = 'unidad' WHERE "SKU" = 'PPG-0022';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img23.jpg', nombre_comercial = 'Repuesto 4 esponja', precio_unitario = 199, unidad_venta = 'unidad' WHERE "SKU" = 'PPG-0023';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img24.png', nombre_comercial = 'ALBERMEX', precio_unitario = 1299, unidad_venta = 'cubeta' WHERE "SKU" = 'PPG-0024';
UPDATE "Producto" SET imagen = '/img/ImagenesPintura/img25.png', nombre_comercial = 'ULTRACRYL TODO', precio_unitario = 1399, unidad_venta = 'cubeta' WHERE "SKU" = 'PPG-0025';
